from enum import Enum


class TenderState(str, Enum):
    INGESTING = "INGESTING"
    INGESTED = "INGESTED"
    SUMMARY_RUNNING = "SUMMARY_RUNNING"
    SUMMARY_READY = "SUMMARY_READY"
    FULL_RUNNING = "FULL_RUNNING"
    FULL_READY = "FULL_READY"
    EVAL_RUNNING = "EVAL_RUNNING"
    EVAL_READY = "EVAL_READY"
    FAILED = "FAILED"
